import csv
import glob
import os
from typing import List, Dict, Any
import json
def getShingles(k, s):
    #perform the trick we discussed to avoid to deal with edge cases
    while(len(s) < k):
        s += ' '

    shingles = {s[i:i+k] for i in range(len(s) - k + 1)}
    return shingles


def getJaccardDistance(a,b):


    if(len(a) == 0 and len(b) == 0):
        return 0

    jaccard = len(a & b) / len(a | b) 
 
    return 1 - jaccard
    


def normalize_key(key: str) -> str:
    """
    Normalize keys like 'handle_youtube' -> 'handle'
    """
    key = key.replace(' ', '')
    if "_" in key:
        base = key.split("_")[0]
        if base in {"handle", "name"}:
            return base
    return key

MISSING_VALUES = {"", "N/A", "NA", "null", "None"}

# Map raw column names -> unified column names
#generated by chatgpt
COLUMN_ALIASES = {
    # names / handles
    "name_instagram": "name",
    "name_youtube": "name",
    "handle_instagram": "handle",
    "handle_youtube": "handle",
    "handle_tiktok": "handle",

    # followers
    "followers": "followers",
    "FOLLOWERS": "followers",

    # country
    "audience_country": "country",
    "COUNTRY": "country",
    "_source_country": "country",

    # engagement
    "engagement_auth": "engagement_rate",
    "engagement_avg": "engagement_avg",
    "ER": "engagement_rate",

    # categories
    "TOPIC OF INFLUENCE": "category_primary",
    "category_1": "category_1",
    "category_2": "category_2",
    "category": "category_primary",
    "category_primary": "category_primary",
    "category_unified": "category_unified",
    "subcategory": "subcategory",

    # performance
    "views_avg": "views_avg",
    "avg_views": "views_avg",
    "likes_avg": "likes_avg",
    "avg_likes": "likes_avg",
    "comments_avg": "comments_avg",
    "avg_comments": "comments_avg",
    "shares_avg": "shares_avg",

    # misc
    "rank": "rank",
    "POTENTIAL REACH": "potential_reach",
    "number_videos_last_year": "number_videos_last_year",
    "processed_at_unix": "processed_at_unix",
    "status": "status",
    "error": "error",
    "exists": "exists",
}


def normalize_key(key: str) -> str:
    key = key.strip()
    return COLUMN_ALIASES.get(key, key.lower().replace(" ", "_"))


def clean_value(value: Any) -> Any:
    if value is None:
        return None

    value = value.strip()
    if value in MISSING_VALUES:
        return None

    return value


def maybe_cast(value: Any) -> Any:
    if value is None:
        return None

    if isinstance(value, str):
        v = value.replace(",", "").strip()

        # bool
        if v.lower() in {"true", "false"}:
            return v.lower() == "true"

        # int
        try:
            if "." not in v:
                return int(v)
        except ValueError:
            pass

        # float
        try:
            return float(v)
        except ValueError:
            pass

    return value


def load_csvs_to_dicts(file_pattern: str) -> List[Dict[str, Any]]:
    all_data: List[Dict[str, Any]] = []

    files = glob.glob(file_pattern)

    for file_path in files:
        file_name = os.path.basename(file_path)

        with open(file_path, mode="r", encoding="utf-8-sig", newline="") as f:
            reader = csv.DictReader(f)

            for row in reader:
                cleaned_row: Dict[str, Any] = {}

                for raw_key, raw_value in row.items():
                    new_key = normalize_key(raw_key)
                    cleaned_value = maybe_cast(clean_value(raw_value))

                    # If multiple columns normalize to same key, prefer non-null
                    if new_key in cleaned_row:
                        if cleaned_row[new_key] is None and cleaned_value is not None:
                            cleaned_row[new_key] = cleaned_value
                    else:
                        cleaned_row[new_key] = cleaned_value

                # Always overwrite/add actual source file name
                cleaned_row["source_file"] = file_name

                all_data.append(cleaned_row)

    return all_data
